ame: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shiri2001/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true shiri2001/react-test npm test
      - run: docker build -t shiri2001/multi-client ./client
      - run: docker build -t shiri2001/multi-nginx ./nginx
      - run: docker build -t shiri2001/multi-server ./server
      - run: docker build -t shiri2001/multi-worker ./worker
      # Log in to the docker CLI
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # Take those images and push them to docker hub
      - run: docker push shiri2001/multi-client
      - run: docker push shiri2001/multi-nginx
      - run: docker push shiri2001/multi-server
      - run: docker push shiri2001/multi-worker

 
   