name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shiri2001/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true shiri2001/react-test npm test
      - run: docker build -t shiri2001/multi-client ./client
      - run: docker build -t shiri2001/multi-nginx ./nginx
      - run: docker build -t shiri2001/multi-server ./server
      - run: docker build -t shiri2001/multi-worker ./worker
      # Log in to the docker CLI
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # Take those images and push them to docker hub
      - run: docker push shiri2001/multi-client
      - run: docker push shiri2001/multi-nginx
      - run: docker push shiri2001/multi-server
      - run: docker push shiri2001/multi-worker

 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker
          environment_name: Docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-996957847444
          bucket_path: docker
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip